### ISSUE TITLE
mc::Util functions only check for single digit subscripts

### ISSUE THREAD

**Issue by notSam25** [notSam25/MultiChem#8]
mc::Util::GetSubscript and mc::Util::GetMolarMass only check for single digit subscripts. Can someone make my life easier and fix this please.

**Comment by ADawesomeguy** [comment]
yeah check my repo. while loop till next non-digit char

**Comment by notSam25** [comment]
> yeah check my repo. while loop till next non-digit char

Do you mind adding into this repo? I'm tired and you can earn github contribution points!

**Comment by notSam25** [comment]
resolved.
